version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: install
          command: 'npm install' 
      - run: 
          name: test
          command: 'npm test'
      - run:
          name: coverage
          command: 'npm run coverage && npm run report-coverage'